export interface Employee {
  id: number,
  fullName: string,
  positionId: number,
  position2Id: number,
  departmentId: number,
  department2Id: number,
  email: string,
  phone: string,
  wosAuthorId: string,
  wosAuthor2Id: string | null,
  scopusAuthorId: string,
  scopusAuthor2Id: string | null,
  rinzAuthorId: string,
  avatarUrl: string,
  academicDegreeId: number,
  academicDegree2Id: number | null,
  academicTitleId: number,
  academicTitle2Id: number | null,
  researcherId: string,
  researcher2Id: string | null,
  commonWorkExperience: number | null,
  specialtyWorkExperience: number | null,
  authorUrlProfile: string,
  authorUrlProfile2: string | null,
  avatarName: string,
  names: any,
  orcid: string,
  researchgate: string,
  spinId: string,
  createdAt: string | null,
  updatedAt: string | null,
  hscopus: string | null,
  hwos: string | null,
  hrinz: string | null
}
